# =================================================
# |                                               |
# |                   SERBLE GEN                  |
# |                                               |
# =================================================


# Default respawn time for generators (Can be manually configured for each gen)
respawn-time: 16
monster-respawn-time: 16

# Worlds that should be included in checks for generators and playtime
gen-worlds:
#  - world

# These are worlds that should have all the fancy shop stuff and xp system etc.
full-featured-worlds:
#  - world

# Items given on initial spawn
starting-items:
#  - ==: org.bukkit.inventory.ItemStack
#    v: 2730
#    type: TRIPWIRE_HOOK
#    meta:
#      ==: ItemMeta
#      meta-type: UNSPECIFIC
#      display-name: '{"extra":[{"bold":true,"italic":false,"color":"gold","text":"Multitool"}],"text":""}'
#      ItemFlags:
#        - HIDE_ENCHANTS
#        - HIDE_ATTRIBUTES
#        - HIDE_UNBREAKABLE
#        - HIDE_DESTROYS
#        - HIDE_PLACED_ON
#        - HIDE_POTION_EFFECTS
#        - HIDE_DYE
#      CanDestroy:
#        - minecraft:wheat
#        - minecraft:stone
#        - minecraft:oak_planks
#      PublicBukkitValues:
#        serblegen:bag_no_interact: '1'
#        serblegen:no_drop: '1'


# Respawn set points
shops:
#  example_shop:
#    world: world
#    points:
#      - 10 63 10 -11 69 -11
#    spawn: 0 64 0 0


# Drops to give to a play who gets lucky and has high XP
drops:
#  example_item:
#    weight: 1
#    command: serbleitem throwable_fireball %s 4-8

# Generators
ore_gens:
#    example_gen:
#      world: world
#      points:
#        - -40 67 -9 -41 67 -8
#
#        - -43 72 -7 -43 72 -13
#        - -43 72 -14 -40 72 -14
#        - -39 72 -14 -39 72 -8
#        - -39 72 -7 -42 72 -7
#
#        - -43 77 -7 -40 77 -7
#        - -39 77 -7 -39 77 -13
#        - -39 77 -14 -42 77 -14
#        - -43 77 -14 -43 77 -8
#      block: POTATOES
#      drop: POTATO
#      perm: allow_potato
#      break-count: 24
#      respawn-time: 24
#      tool: Hoe

